# Generated by Django 4.0.2 on 2022-02-09 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_booking_date_booking_doctor_booking_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timeslot',
            name='slot',
        ),
        migrations.AddField(
            model_name='timeslot',
            name='end_time',
            field=models.TimeField(max_length=1, null=True, verbose_name='End time'),
        ),
        migrations.AddField(
            model_name='timeslot',
            name='start_time',
            field=models.TimeField(max_length=1, null=True, verbose_name='Start time'),
        ),
    ]
