# Generated by Django 4.0.2 on 2022-02-09 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0005_remove_timeslot_slot_timeslot_end_time_and_more'),
    ]

    operations = [

    ]
