# Generated by Django 4.0.2 on 2022-02-09 21:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('setting', '0001_initial'),
        ('doctor', '0025_alter_doctortimeslot_unique_together_and_more'),
        ('patient', '0001_initial'),
        ('booking', '0009_booking_patient'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='consultation_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='bookings', to='setting.consultation', verbose_name='Consultation Type'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='doctor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='bookings', to='doctor.doctor', verbose_name='Doctor'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='patient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='bookings', to='patient.patient', verbose_name='Patient'),
        ),
    ]
