# Generated by Django 4.0.2 on 2022-02-09 22:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('setting', '0001_initial'),
        ('booking', '0010_booking_consultation_type_alter_booking_doctor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='price',
            field=models.FloatField(null=True, verbose_name='Price'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='consultation_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='bookings', to='setting.consultation', verbose_name='Consultation type'),
        ),
    ]
