# Generated by Django 4.0.2 on 2022-02-11 19:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0029_rename_address_ar_doctor_address_and_more'),
        ('booking', '0011_booking_price_alter_booking_consultation_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='start_time',
        ),
        migrations.AddField(
            model_name='booking',
            name='time',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='time', to='doctor.doctortimeslot', verbose_name='Time'),
        ),
    ]
