# Generated by Django 4.0.2 on 2022-02-09 21:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('setting', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientOTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=255, null=True, verbose_name='Phone')),
                ('code', models.CharField(max_length=6, null=True, verbose_name='Code')),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created')),
                ('updated', models.DateTimeField(auto_now=True, null=True, verbose_name='Updated')),
                ('country', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='otp', to='setting.country', verbose_name='Country')),
            ],
            options={
                'verbose_name': 'Patient OTP',
                'verbose_name_plural': 'Patients OTP',
            },
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_en', models.CharField(max_length=255, null=True, verbose_name='Name')),
                ('name_ar', models.CharField(max_length=255, null=True, verbose_name='Name')),
                ('name_ro', models.CharField(max_length=255, null=True, verbose_name='Name')),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1, null=True)),
                ('picture', models.ImageField(blank=True, null=True, upload_to='doctors/profile_pictures', verbose_name='Picture')),
                ('phone', models.CharField(max_length=255, null=True, verbose_name='Phone')),
                ('address_en', models.TextField(null=True, verbose_name='Address')),
                ('address_ar', models.TextField(null=True, verbose_name='Address')),
                ('address_ro', models.TextField(null=True, verbose_name='Address')),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created')),
                ('updated', models.DateTimeField(auto_now=True, null=True, verbose_name='Updated')),
                ('city', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='patients', to='setting.city', verbose_name='City')),
                ('country', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='patients', to='setting.country', verbose_name='Country')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='patient', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Patient',
                'verbose_name_plural': 'Patients',
            },
        ),
    ]
