# Generated by Django 4.0.2 on 2022-02-11 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='address_ar',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='name_ar',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='address_en',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='address_ro',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='name_en',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='name_ro',
        ),
    ]
