# Generated by Django 4.0.2 on 2022-02-09 19:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0004_rename_address_doctor_address_ar_doctor_address_en_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorConsultation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField(null=True, verbose_name='Price')),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created')),
                ('updated', models.DateTimeField(auto_now=True, null=True, verbose_name='Updated')),
                ('doctor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='consultation', to='doctor.doctor', verbose_name='Doctor')),
            ],
            options={
                'verbose_name': 'Doctor Consultation',
                'verbose_name_plural': 'Doctor Consultations',
            },
        ),
    ]
