# Generated by Django 4.0.2 on 2022-02-09 19:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0006_doctorconsultation_consultation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorconsultation',
            name='doctor',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='consultations', to='doctor.doctor', verbose_name='Doctor'),
        ),
    ]
