# Generated by Django 4.0.2 on 2022-02-09 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0013_alter_doctor_specialities'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='doctors/profile_pictures', verbose_name='Picture'),
        ),
    ]
