# Generated by Django 4.0.2 on 2022-02-09 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0014_doctor_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='bio_ar',
            field=models.TextField(null=True, verbose_name='Bio'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='bio_en',
            field=models.TextField(null=True, verbose_name='Bio'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='bio_ro',
            field=models.TextField(null=True, verbose_name='Bio'),
        ),
    ]
