# Generated by Django 4.0.2 on 2022-02-09 21:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('setting', '0001_initial'),
        ('doctor', '0016_doctor_gender'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorInsuranceCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.FloatField(null=True, verbose_name='Number')),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created')),
                ('updated', models.DateTimeField(auto_now=True, null=True, verbose_name='Updated')),
                ('doctor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='insurance_companies', to='doctor.doctor', verbose_name='Doctor')),
                ('insurance_company', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='doctors', to='setting.insurancecompany', verbose_name='Consultation')),
            ],
            options={
                'verbose_name': 'Doctor Insurance Company',
                'verbose_name_plural': 'Doctor Insurance companies',
                'unique_together': {('doctor', 'insurance_company')},
            },
        ),
    ]
