# Generated by Django 4.0.2 on 2022-02-09 21:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_booking_date_booking_doctor_booking_time'),
        ('doctor', '0019_alter_doctorinsurancecompany_insurance_company'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorTimeSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created')),
                ('updated', models.DateTimeField(auto_now=True, null=True, verbose_name='Updated')),
                ('doctor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='doctor.doctor', verbose_name='Doctor')),
                ('slot', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='doctors', to='booking.timeslot', verbose_name='Time slot')),
            ],
            options={
                'verbose_name': 'Doctor time slot',
                'verbose_name_plural': 'Doctor time slots',
                'unique_together': {('doctor', 'slot')},
            },
        ),
    ]
