# Generated by Django 4.0.2 on 2022-02-09 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0020_doctortimeslot'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctortimeslot',
            name='is_free',
            field=models.BooleanField(default=True, null=True, verbose_name='Is free'),
        ),
    ]
