# Generated by Django 4.0.2 on 2022-02-09 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0021_doctortimeslot_is_free'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctortimeslot',
            name='note',
            field=models.TextField(null=True, verbose_name='Note'),
        ),
    ]
