# Generated by Django 4.0.2 on 2022-02-09 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0022_doctortimeslot_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctortimeslot',
            name='note',
            field=models.CharField(max_length=255, null=True, verbose_name='Note'),
        ),
    ]
