# Generated by Django 4.0.2 on 2022-02-11 17:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('setting', '0003_alter_insurancecompany_country'),
        ('doctor', '0026_alter_doctor_gender'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorOTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=255, null=True, verbose_name='Phone')),
                ('code', models.CharField(max_length=6, null=True, verbose_name='Code')),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created')),
                ('updated', models.DateTimeField(auto_now=True, null=True, verbose_name='Updated')),
                ('country', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='doctor_otp', to='setting.country', verbose_name='Country')),
            ],
            options={
                'verbose_name': 'Doctor OTP',
                'verbose_name_plural': 'Doctors OTP',
            },
        ),
    ]
